name: Node.js CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          cd frontend
          npm ci
          npm run build
      - name: Login to AppVenture registry
        uses: docker/login-action@v3
        with:
          registry: registry.nush.app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v5
        with:
          context: server
          push: true
          tags: registry.nush.app/arxiv-nush:backend
      - name: Push image to AppVenture registry
        uses: docker/build-push-action@v5
        with:
          context: frontend
          push: true
          tags: registry.nush.app/arxiv-nush:frontend